# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        AddWindow.setObjectName("AddWindow")
        AddWindow.resize(413, 579)
        self.centralwidget = QtWidgets.QWidget(AddWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.SettingLabel = QtWidgets.QLabel(self.centralwidget)
        self.SettingLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.SettingLabel.setFont(font)
        self.SettingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SettingLabel.setObjectName("SettingLabel")
        self.gridLayout.addWidget(self.SettingLabel, 0, 0, 1, 2)
        self.settingVLay = QtWidgets.QVBoxLayout()
        self.settingVLay.setObjectName("settingVLay")
        self.matchLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.matchLabel.setFont(font)
        self.matchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.matchLabel.setObjectName("matchLabel")
        self.settingVLay.addWidget(self.matchLabel)
        self.gridLayout.addLayout(self.settingVLay, 1, 0, 1, 1)
        self.settingVLay2 = QtWidgets.QVBoxLayout()
        self.settingVLay2.setObjectName("settingVLay2")
        self.nameMatch = QtWidgets.QLineEdit(self.centralwidget)
        self.nameMatch.setMaximumSize(QtCore.QSize(500, 16777215))
        self.nameMatch.setText("")
        self.nameMatch.setObjectName("nameMatch")
        self.settingVLay2.addWidget(self.nameMatch)
        self.gridLayout.addLayout(self.settingVLay2, 1, 1, 1, 1)
        self.settingHLay = QtWidgets.QHBoxLayout()
        self.settingHLay.setObjectName("settingHLay")
        self.tutorialBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tutorialBtn.setFont(font)
        self.tutorialBtn.setObjectName("tutorialBtn")
        self.settingHLay.addWidget(self.tutorialBtn)
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.settingHLay.addWidget(self.saveBtn)
        self.gridLayout.addLayout(self.settingHLay, 2, 0, 1, 2)
        self.actionLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionLabel.sizePolicy().hasHeightForWidth())
        self.actionLabel.setSizePolicy(sizePolicy)
        self.actionLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.actionLabel.setText("")
        self.actionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionLabel.setObjectName("actionLabel")
        self.gridLayout.addWidget(self.actionLabel, 3, 0, 1, 2)
        AddWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 413, 26))
        self.menubar.setObjectName("menubar")
        AddWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddWindow)
        self.statusbar.setObjectName("statusbar")
        AddWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddWindow)
        QtCore.QMetaObject.connectSlotsByName(AddWindow)

    def retranslateUi(self, AddWindow):
        _translate = QtCore.QCoreApplication.translate
        AddWindow.setWindowTitle(_translate("AddWindow", "Add Source"))
        self.SettingLabel.setText(_translate("AddWindow", "Settings:"))
        self.matchLabel.setText(_translate("AddWindow", "Name Match Value:"))
        self.tutorialBtn.setText(_translate("AddWindow", "Tutorial"))
        self.saveBtn.setText(_translate("AddWindow", "Save"))
